[2025-03-16T21:51:31.942+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T21:51:32.107+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.process_stations_data manual__2025-03-16T21:51:17.045850+00:00 [queued]>
[2025-03-16T21:51:32.269+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.process_stations_data manual__2025-03-16T21:51:17.045850+00:00 [queued]>
[2025-03-16T21:51:32.287+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-16T21:51:32.448+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_stations_data> on 2025-03-16 21:51:17.045850+00:00
[2025-03-16T21:51:32.524+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=570) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-16T21:51:32.544+0000] {standard_task_runner.py:72} INFO - Started process 592 to run task
[2025-03-16T21:51:32.553+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'process_stations_data', 'manual__2025-03-16T21:51:17.045850+00:00', '--job-id', '687', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpu0zafpo3']
[2025-03-16T21:51:32.559+0000] {standard_task_runner.py:105} INFO - Job 687: Subtask process_stations_data
[2025-03-16T21:51:33.006+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.process_stations_data manual__2025-03-16T21:51:17.045850+00:00 [running]> on host 5c7a1daace86
[2025-03-16T21:51:33.681+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='process_stations_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T21:51:17.045850+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T21:51:17.045850+00:00'
[2025-03-16T21:51:33.692+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-16T21:51:33.719+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-16T21:51:33.725+0000] {logging_mixin.py:190} INFO - Current task name:process_stations_data state:running start_date:2025-03-16 21:51:32.127206+00:00
[2025-03-16T21:51:33.735+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-03-16T21:51:33.759+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-16T21:51:37.189+0000] {data_ingestion_gcs_dag.py:82} INFO - Uploaded /opt/***/indego-stations-2025-01-01.parquet to gs://<Bucket: kestra-de-zoomcamp-bucket-kelly>/raw/indego_stations.parquet
[2025-03-16T21:51:37.201+0000] {data_ingestion_gcs_dag.py:146} INFO - Uploaded /opt/***/indego-stations-2025-01-01.parquet to GCS.
[2025-03-16T21:51:37.216+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-16T21:51:37.360+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-16T21:51:37.367+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=process_stations_data, run_id=manual__2025-03-16T21:51:17.045850+00:00, execution_date=20250316T215117, start_date=20250316T215132, end_date=20250316T215137
[2025-03-16T21:51:37.461+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-16T21:51:37.493+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-16T21:51:37.506+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag queued_at:2025-03-16 21:51:17.198952+00:00
[2025-03-16T21:51:37.522+0000] {logging_mixin.py:190} INFO - Task hostname:5c7a1daace86 operator:PythonOperator
[2025-03-16T21:51:37.598+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-16T21:51:37.672+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-16T21:51:37.776+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T21:51:37.818+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
